version: "3"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: gswap
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  processor:
    build:
      context: .
      target: processor
    environment:
      - DB_NAME=gswap
      - DB_PORT=5432
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - RPC_ENDPOINT
      - ARCHIVE_URL
    depends_on:
      - db
    command: ["sqd", "process"]

  api:
    build:
      context: .
      target: api
    environment:
      - DB_NAME=gswap
      - DB_PORT=5432
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
    ports:
      - "4350:3000"
    depends_on:
      - db
    command: ["sqd", "serve"]

volumes:
  db_data:
